[build]
  command = "./build.js"
  publish = "build/"

[build.environment]
  NODE_VERSION = "24.15.0"
  NPM_VERSION = "12.0.1"

[[redirects]]
  from = "https://the-infi-way.netlify.app"
  to = "https://way.infi.nl"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"
