name: Deploy to GitHub Pages

on:
  push:
    branches:
      - localization-handlebars-lite-poc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          node -v
